version: '3.3'

services:
    api:
        build:
            context: .
            dockerfile: ./Docker/api/Dockerfile
        ports:
            - '5000:5000'
    frontend:
        build:
            context: .
            dockerfile: ./Docker/frontend/Dockerfile
        ports:
            - '80:3000'
